import { configureTestRuntimeMetadata } from '../../../test/runtime-metadata'
import { describe, expect, it } from 'vitest'
import { exportRisFields, importRisFields } from './citation-exchange'
import { LiteratureCitationFormatter } from './citation-formatter'

// Fixed historical bytes, deliberately not generated by today's exporter.
const oldBook = `TY  - BOOK
TI  - Legacy institutions
A3  - Department, University
N1  - Open Science literal creator: ["A3",0,"Department, University"]
A4  - Translation, Institute
N1  - Open Science literal creator: ["A4",0,"Translation, Institute"]
ER  -
`
const oldArticle = `TY  - JOUR
TI  - Legacy article
A2  - Department, University
N1  - Open Science literal creator: ["A2",0,"Department, University"]
A4  - Translation, Institute
N1  - Open Science literal creator: ["A4",0,"Translation, Institute"]
ER  -
`

describe('RIS literal creator compatibility', () => {
  it.each([oldBook, oldArticle])(
    'imports historical institution names through the formatter',
    async (input) => {
      const result = await new LiteratureCitationFormatter().parseReferences(input)
      expect(result.errors).toEqual([])
      expect(result.items[0]?.creators).toEqual([
        { creatorType: 'editor', nameMode: 'organization', literalName: 'Department, University' },
        {
          creatorType: 'translator',
          nameMode: 'organization',
          literalName: 'Translation, Institute'
        }
      ])
    }
  )

  it.each(['book', 'article-journal'])('writes only new markers and round-trips %s', (type) => {
    const item = {
      id: 'x',
      title: 'Institutions',
      type,
      editor: [{ literal: 'Department, University' }],
      translator: [{ literal: 'Translation, Institute' }]
    }
    const text = exportRisFields(item)
    expect(text).toContain('Open-Science literal creator: ')
    expect(text).not.toContain('Open Science literal creator: ')
    expect(importRisFields(text, { type })).toMatchObject({
      editor: item.editor,
      translator: item.translator
    })
  })

  it.each(['Open Science literal creator: ', 'Open-Science literal creator: '])(
    'validates all %s markers against the visible tag, index and value',
    (prefix) => {
      for (const marker of [
        '{broken',
        '{}',
        '["A3",-1,"Department, University"]',
        '["A3",99,"Department, University"]',
        '["A3","0","Department, University"]',
        '["A4",0,"Department, University"]',
        '["A3",0,"Changed, Institution"]',
        '["A3",0,42]',
        '["A3",0,"Department, University","extra"]'
      ]) {
        const result = importRisFields(`A3  - Department, University\nN1  - ${prefix}${marker}\n`, {
          type: 'book'
        })
        expect(result.editor, marker).toEqual([{ family: 'Department', given: 'University' }])
      }
      const reordered = `A3  - Person, Ada\nA3  - Department, University\nN1  - ${prefix}["A3",0,"Department, University"]\n`
      expect(importRisFields(reordered, { type: 'book' }).editor).toEqual([
        { family: 'Person', given: 'Ada' },
        { family: 'Department', given: 'University' }
      ])
    }
  )

  it('ignores unknown notes and notes outside the record', () => {
    expect(
      importRisFields(
        'A3  - Department, University\nN1  - Unknown literal creator: ["A3",0,"Department, University"]\nER  -\nN1  - Open Science literal creator: ["A3",0,"Department, University"]',
        { type: 'book' }
      ).editor
    ).toEqual([{ family: 'Department', given: 'University' }])
  })
})

configureTestRuntimeMetadata()
