import type { TurnOutcome } from './turn-outcome'
import {
  type AcpMessageImage,
  type AcpTurnTokenUsage,
  type AcpModelCallUsage,
  type AcpContextWindowSample,
  MAX_ACP_RUNTIME_EVENTS
} from '../acp'
import type { LiteratureItemInput } from '../literature'
import type { FileReference } from '../artifacts'
import type { AgentFrameworkId, ReasoningEffort } from '../settings'
import type { PersistedUploadedAttachment } from '../uploads'
import type { Annotation } from '../annotations'
import type { DelegatedCallerSource, MessagePdfContextSnapshot } from '../session-runtime-context'
import type { ElicitationProjection } from '../elicitation'

export type PersistedMessageRole = 'user' | 'agent'

export type PersistedMessageStatus = 'complete' | 'streaming' | 'error'

export type MessageAttribution =
  | Readonly<{
      kind: 'application'
      feature: 'reviewer'
      purpose: 'correction'
      causeReviewId: string
      // Durable ownership of this correction round; Resume must not replenish its budget.
      continuation?: { round: number; maxRounds: number; findingIds: string[] }
    }>
  | Readonly<{
      kind: 'application'
      feature: 'compute'
      purpose: 'job-completion-analysis'
      deliveryKey: string
      jobIds: string[]
    }>
  | Readonly<{
      kind: 'application'
      feature: 'background-results'
      purpose: 'agent-result-delivery'
      deliveryKey: string
      deliveryIds: string[]
    }>

// Managed files are generated by the app artifact pipeline; the other kinds are reserved references.
export type PersistedArtifactKind = 'workspace-file' | 'external-file' | 'managed-file'

// Stores artifact references only; file bytes stay on disk under the managed artifact root.
export type PersistedArtifact = {
  id: string
  artifactId?: string
  versionId?: string
  versionNumber?: number
  kind: PersistedArtifactKind
  path: string
  fileUrl?: string
  name?: string
  mimeType?: string
  size?: number
  createdAt?: number
  mtimeMs?: number
  sha256?: string
}

export type PersistedMessageImage = AcpMessageImage & {
  id: string
}

export type SessionReference = { type: 'session'; sessionId: string; title: string }

export const MAX_SESSION_REFERENCES_PER_MESSAGE = 5

export const MAX_SESSION_REFERENCE_ID_LENGTH = 512

export const MAX_SESSION_REFERENCE_TITLE_LENGTH = 4096

// Immutable bibliographic snapshot captured when the user picks a Library item. The optional PDF
// Version is only a Reading candidate; the reference itself remains useful without an attachment.
export type LiteratureReference = {
  type: 'literature'
  itemId: string
  metadataRevision: number
  item: LiteratureItemInput
  attachmentVersionId?: string
}

// A retrieval scope selected in the Composer. It carries no catalog records or file bytes; the Agent
// uses it to page through search_library deliberately instead of treating a whole corpus as context.
export type LiteratureScopeReference =
  | { type: 'literature-scope'; scope: 'project' }
  | { type: 'literature-scope'; scope: 'collection'; collectionId: string; name: string }

export const MAX_LITERATURE_SCOPE_ID_LENGTH = 512

export const MAX_LITERATURE_SCOPE_NAME_LENGTH = 4096

// Ordered structural segments of a user message, letting the bubble re-render skill/artifact/session
// mentions as styled pills instead of plain text. Structurally mirrors the renderer ComposerNode
// (shared cannot import renderer code). Absent on older messages, which fall back to plain content.
export type MessagePart =
  | { type: 'text'; text: string }
  | { type: 'skill'; id: string; name: string }
  | ({ type: 'artifact' } & FileReference)
  | LiteratureReference
  | LiteratureScopeReference
  | SessionReference

export const collectSessionReferences = (
  parts: readonly MessagePart[] | undefined
): SessionReference[] => {
  const references: SessionReference[] = []
  for (const part of parts ?? []) {
    if (
      part.type !== 'session' ||
      references.some((reference) => reference.sessionId === part.sessionId)
    ) {
      continue
    }
    references.push({ type: 'session', sessionId: part.sessionId, title: part.title })
    if (references.length >= MAX_SESSION_REFERENCES_PER_MESSAGE) break
  }
  return references
}

// The resolved Agent target a user Message was sent with. Consecutive snapshots let the renderer
// derive session config-change timeline markers without a synthetic activity. Absent on messages
// persisted before the field existed; unknown values are discarded by the persistence sanitizer.
export type PersistedMessageAgentTarget = {
  frameworkId: AgentFrameworkId
  backendId?: string
  providerId: string
  model?: string
  reasoningEffort: ReasoningEffort
}

// Non-authoritative UI identity retained when renderer-originated Compute attribution is stripped
// at the main-process trust boundary. Delivery recovery and authorization must never consume it.
export type PersistedMessagePresentation = Readonly<{
  kind: 'compute-job-completion'
}>

export type PersistedChatMessage = {
  id: string
  role: PersistedMessageRole
  content: string
  attribution?: MessageAttribution
  presentation?: PersistedMessagePresentation
  agentTarget?: PersistedMessageAgentTarget
  status: PersistedMessageStatus
  streamId?: string
  responseToMessageId?: string
  eventIds: string[]
  // Links a message to session-level artifact metadata without duplicating file records per message.
  artifactIds?: string[]
  uploads?: PersistedUploadedAttachment[]
  // Structured evidence staged with the Composer and sent as part of this user Message.
  annotations?: Annotation[]
  // Delegate assignment metadata keeps execution inputs reconstructable without parsing display text.
  delegatedTask?: string
  delegatedInputVersionIds?: string[]
  // Durable source of a Main-to-child ACP Turn. Frame origin remains immutable lineage only.
  delegatedCallerSource?: DelegatedCallerSource
  // Bounded raster blocks emitted directly by ACP agent_message_chunk notifications.
  images?: PersistedMessageImage[]
  // Structured mention segments for the styled user bubble; optional for backward compatibility.
  parts?: MessagePart[]
  // Immutable PDF context captured when this user turn was admitted. It remains independent from
  // the Session's mutable binding so queue, retry, edit-resend, and interrupted resume cannot drift.
  pdfContext?: MessagePdfContextSnapshot
  // Settled result of the turn this user Message anchors; absent until Main settles it.
  turnOutcome?: TurnOutcome
  // Closed turn identity needed to reconstruct an interrupted turn after an app restart. Ordinary
  // messages omit it; unknown values are discarded by the persistence sanitizer.
  turnIntent?: 'plan-first' | 'save-as-skill'
  // A side-chat relay is durable context, but remains advisory rather than a direct user turn.
  relayedFrom?: { kind: 'side-chat'; direction: 'to-main' }
  // Whole-turn totals reported with the completed Agent response; absent for older sessions/providers.
  // Copied history remains visible, but its execution belongs to the original Session.
  usageOrigin?: Readonly<{ sessionId: string; messageId: string }>
  turnUsage?: AcpTurnTokenUsage
  // Exact per-inference usage; absent for older sessions/providers and whenever coverage is partial.
  modelCallUsage?: AcpModelCallUsage[]
  // Terminal last-model-step context-window snapshots for each visible execution of this user Message.
  contextWindowSamples?: AcpContextWindowSample[]
  // Marks the final Agent message for a turn whose provider did not report usable totals.
  turnUsageUnavailable?: true
  structuredOutputEvidence?: Readonly<{
    attemptId: string
    dialect: '2020-12'
    profile: 'ajv-8-draft-2020-12-v1'
    schemaDigest: string
    schema: unknown
    accepted?: Readonly<{ value: unknown; acceptedAt: number }>
  }>
  structuredOutputEvidenceInvalid?: true
  createdAt: number
  // Stable terminal timestamps survive later artifact/upload reconciliation that advances updatedAt.
  completedAt?: number
  failedAt?: number
  // Durable marker for a user turn whose provider interaction ended without a terminal response.
  // Resume preserves this exact Message node; it never creates a replacement prompt.
  interrupted?: true
  updatedAt: number
}

// Runtime recovery can replay only its bounded suffix. Once a projection is terminal, older IDs no
// longer provide supported duplicate-suppression coverage and must not grow the Session forever.
export const retainRecentSessionEventIds = (eventIds: readonly string[]): string[] => {
  if (eventIds.length <= MAX_ACP_RUNTIME_EVENTS) return [...eventIds]

  const recent: string[] = []
  const seen = new Set<string>()
  for (
    let index = eventIds.length - 1;
    index >= 0 && recent.length < MAX_ACP_RUNTIME_EVENTS;
    index--
  ) {
    const eventId = eventIds[index]
    if (eventId === undefined || seen.has(eventId)) continue
    seen.add(eventId)
    recent.push(eventId)
  }
  return recent.reverse()
}

export const isHiddenControlMessage = (
  message: Pick<PersistedChatMessage, 'turnIntent'>
): boolean => message.turnIntent === 'save-as-skill'

export const isHumanUserMessage = (
  message: Pick<PersistedChatMessage, 'role' | 'attribution' | 'presentation' | 'relayedFrom'>
): boolean =>
  message.role === 'user' && !message.attribution && !message.presentation && !message.relayedFrom

export type PersistedToolActivityStatus = 'pending' | 'in_progress' | 'completed' | 'failed'

export type PersistedToolActivityDisposition = 'declined' | 'permission-closed'

// A file location a tool touched; kept small so it can always be persisted.
export type PersistedToolCallLocation = {
  path: string
  line?: number | null
}

// Durable projection of a runtime tool call. Large payloads are bounded (see caps below) so
// restoring the transcript never bloats sessions.json; the UI already truncates the same fields.
export type PersistedToolActivity = {
  id: string
  kind: 'tool'
  title: string
  activityGroupId?: string
  promptMessageId?: string
  status: PersistedToolActivityStatus
  toolDisposition?: PersistedToolActivityDisposition
  executionInvocationId?: string
  // Set only by the main-process permission owner, never by provider metadata.
  appOwned?: true
  sortIndex: number
  eventIds: string[]
  providerToolName?: string
  toolKind?: string
  // Structurally a subset of ACP ToolCallContent[]; typed loosely to keep shared free of the SDK.
  toolContent?: unknown[]
  toolLocations?: PersistedToolCallLocation[]
  rawInput?: unknown
  rawOutput?: unknown
  terminalOutput?: string
  terminalExitCode?: number | null
  elicitation?: ElicitationProjection
  createdAt: number
  updatedAt: number
}

export type PersistedActivityGroup = {
  id: string
  title: string
  sortIndex: number
  activityIds: string[]
  promptMessageId?: string
  createdAt: number
  updatedAt: number
  completedAt?: number
}
